### PR TITLE
Feature/karseng feat accept float64

### PR DESCRIPTION
**Pull request by agmo-karseng**

### CODE REVIEW

**Comment by zezo357** [comment]
Hello,

May I ask why it was closed?

Also, please note that I did try using `float64` and it didn't work as expected in my case. However, if you've been able to make it work, I don't mind the change.

**Comment by agmo-karseng** [comment]
Hello,

I accidentally created a PR while trying out using float64 on my side, sorry for the inconvenience.

**Comment by zezo357** [comment]
will see the output of the integration tests, i think its not working correctly on ios btw, (i mean the changing type [use Float64 as input instead of uint8list](https://github.com/zezo357/pytorch_lite/pull/48/commits/7cb5ebc3438659a4993a20d5e736635f6776aae0))

**Comment by zezo357** [comment]
and the classification doesnt even run on android :_(

**Pull request closed without merging**
